EcomProj/urls.py
from django.conf import settings
from django.conf.urls.static import static
from django.contrib import admin
from django.urls import path,include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('',include('Products.urls')),
    path('SupAdmin/',include('SupAdmin.urls')),
]

if settings.DEBUG:
    urlpatterns+=static(settings.STATIC_URL,document_root=settings.STATIC_ROOT)
    urlpatterns+=static(settings.MEDIA_URL,document_root=settings.MEDIA_ROOT)

Products/models.py
from django.db import models
from django.contrib.auth.models import User

# Create your models here.
class User_info(models.Model):
    user = models.OneToOneField(User,on_delete=models.CASCADE,blank=False,null=False)
    GENDER_CHOICE= (('M','Male'),('F','Female'),('OG','Other'))
    profile_pic = models.ImageField(upload_to='profilepic',blank=False,null=False)
    gender = models.CharField(max_length=10,choices=GENDER_CHOICE,blank=False,null=False)
    address = models.CharField(max_length=100,blank=False,null=False)
    phone = models.CharField(max_length=15,blank=False,null=False)

    def __str__(self):
        return "User: {},Genger: {}".format(self.user.first_name, self.gender)



class Category(models.Model):
    name = models.CharField(max_length=20)
    date = models.DateTimeField(auto_now_add=True)    
    

    def __str__(self):
        return self.name


    @staticmethod
    def get_all_category():
        return Category.objects.all()


class Product(models.Model):
    name = models.CharField(max_length=50)
    price = models.IntegerField(default=0)
    unit = models.CharField(max_length = 15,blank=True)
    description = models.TextField(max_length=1000,null=False)
    category = models.ForeignKey(Category,on_delete=models.CASCADE,default=1)
    image = models.ImageField(upload_to = 'products/')


    def __str__(self):
        return self.name

    @staticmethod
    def get_product_by_id(ids):
        return Product.objects.filter(id__in = ids)

    @staticmethod
    def get_all_products():
        return Product.objects.all()

    @staticmethod
    def get_all_products_by_categoryid(categoryid):
        if categoryid:
            return Product.objects.filter(category = categoryid)
        else:
            return Product.objects.all()


class Order(models.Model):
    user = models.ForeignKey(User, on_delete=models.CASCADE)
    product = models.ForeignKey(Product, on_delete=models.CASCADE)
    quantity = models.IntegerField()
    price = models.IntegerField()
    bkashTrxID = models.CharField(max_length=150,default='',blank=True)
    address = models.CharField(max_length=150,default='')
    phone = models.CharField(max_length=15,default='')
    status = models.BooleanField(default=False)
    date = models.DateTimeField(auto_now_add=True)

    def __str__(self):
        return self.address
    
    
    def placeOrder(self):
        self.save()

    @staticmethod
    def get_orders_by_customer(customer_id):
        return Order.objects.filter(user = customer_id).order_by('-id')
    

templates/base.html
{% load mycheck %}
<!doctype html>
<html lang="en">
  <head>
    <!-- Required meta tags -->
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">

    <!-- Bootstrap CSS -->
    <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap@4.6.0/dist/css/bootstrap.min.css" integrity="sha384-B0vP5xmATw1+K9KRQjQERJvTumQW0nPEzvF6L/Z6nronJ3oUOFUFpCjEUQouq2+l" crossorigin="anonymous">

    <title>Proyojon Shop | {% block title %}{% endblock %}</title>
  </head>
  <body>
    {% include 'navbar.html' %}
    
    {% block content %}
    
    {% endblock %}
    <!-- Optional JavaScript; choose one of the two! -->

    <!-- Option 1: jQuery and Bootstrap Bundle (includes Popper) -->
    <script src="https://code.jquery.com/jquery-3.5.1.slim.min.js" integrity="sha384-DfXdz2htPH0lsSSs5nCTpuj/zy4C+OGpamoFVy38MVBnE+IbbVYUew+OrCXaRkfj" crossorigin="anonymous"></script>
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@4.6.0/dist/js/bootstrap.bundle.min.js" integrity="sha384-Piv4xVNRyMGpqkS2by6br4gNJ7DXjqk09RmUpJ8jgGtD7zP9yug3goQfGII0yAns" crossorigin="anonymous"></script>

    <!-- Option 2: Separate Popper and Bootstrap JS -->
    <!--
    <script src="https://code.jquery.com/jquery-3.5.1.slim.min.js" integrity="sha384-DfXdz2htPH0lsSSs5nCTpuj/zy4C+OGpamoFVy38MVBnE+IbbVYUew+OrCXaRkfj" crossorigin="anonymous"></script>
    <script src="https://cdn.jsdelivr.net/npm/popper.js@1.16.1/dist/umd/popper.min.js" integrity="sha384-9/reFTGAW83EW2RDu2S0VKaIzap3H66lZH81PoYlFhbGU+6BZp6G7niu735Sk7lN" crossorigin="anonymous"></script>
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@4.6.0/dist/js/bootstrap.min.js" integrity="sha384-+YQ4JLhjyBLPDQt//I+STsc9iw4uQqACwlvpslubQzn4u2UU2UFM80nGisd026JF" crossorigin="anonymous"></script>
    -->
  </body>
</html>

templates/cart.html
{% extends 'base.html' %}
{% load mycheck %}


{% block title %}
Cart
{% endblock %}

{% comment %} body {% endcomment %}
{% block content %}
<div class="container">

  <div class="border rounded p-4 m-3">
    <h1 class='text-center'>Cart List</h1>
    <table class="table">
      <thead>
        <tr>
          <th>Sno.</th>
          <th>Image</th>
          <th>Name</th>
          <th>Category</th>
          <th>Price</th>
          <th>Quantity</th>
          <th>Total Price</th>
        </tr>
      </thead>
      <tbody>
        
    {% for product in products %}
        <tr>          
          <td>{{ forloop.counter }}</td>
          <td>
            <a href="{% url 'productdetail' product.id %}">
            <img src="{{ product.image.url }}" width="100px" height="100px" alt="">
          </a>
          </td>
          <td>{{ product.name}}</td>
          <td>{{ product.category}}</td>
          <td>{{ product.price|currency }}/{{product.unit}}</td>
          <td>
            <form action="{% url 'incdec' %}" class="col-3 p-0 btn btn-success" method="post">
              {% csrf_token %}
              <input type="text" hidden name="productid" value="{{product.id}}" id="">
              <input type="text" hidden name="remove" value="True" id="">
              <input type="submit" class='m-0 btn btn-success ' value="-">
          </form>
            {{ product|cart_quantity:request.session.cart}}{{product.unit}}
            <form action="{% url 'incdec' %}" class="col-3 p-0 btn btn-success" method="post">
              {% csrf_token %}
              <input type="text" hidden name="productid" value="{{product.id}}" id="">
              <input type="submit" class='btn btn-success' value="+">
          </form>
          </td>
          <td>{{ product|price_total:request.session.cart|currency  }}</td>
        </tr>
    {% endfor %}
        
      </tbody>
      <tfoot>
        <tr>
          <td  colspan="5"></td>
          <td>Total</td>        
          <td>= {{ products|total_cart_price:request.session.cart|currency }}</td>
        </tr>
      </tfoot>
    </table>
{% if request.user.is_authenticated %}
    {% if request.session.cart %}
    <div class="p-3 m-3">
      <a href="#"  class="btn btn-info float-right btn btn-primary" data-toggle="modal" data-target="#exampleModal">Check Out</a>
    </div>
    {% endif %}
    {% else %}
    <div class="p-3 m-3">
      <a href="{% url 'signin' %}"  class="btn btn-info float-right btn btn-primary">Login</a>
    </div>
  {% endif %}
   
  </div>
   
</div>


<!-- Button trigger modal -->
{% if request.user.is_authenticated %}
<!-- Modal -->

<div class="modal fade" id="exampleModal" tabindex="-1" aria-labelledby="exampleModalLabel" aria-hidden="true">
  <div class="modal-dialog">
    <div class="modal-content">
      <div class="modal-header">
        <h5 class="modal-title" id="exampleModalLabel">Check Out Form</h5>
        <button type="button" class="close" data-dismiss="modal" aria-label="Close">
          <span aria-hidden="true">&times;</span>
        </button>
      </div>

      <div class="modal-body">
        <div class="p-1 m-1">
          <div class="payment">
            <p class="text-center">*Make your payment in this number through any bKash Customer Wallet <br><small><a href="#paymentinst">payment instruction</a></small></p>
            <hr>
            <h4 class="text-center">Amount of Taka = {{ products|total_cart_price:request.session.cart|currency }}</h4>
            <hr>
            <h4 class="text-center text-success"><small class="text-danger">Merchant bKash No:</small> 01879205233</h4><hr>
          </div>
          <form action="{% url 'checkout' %}" method="POST">
          {% csrf_token %}
          <div class="form-group">
            <label for="bkashtrxid">Enter bKash TrxID:<span class="text-danger">*</span> </label>
            <input type="text" name="bkashtrxid" id="bkashtrxid" class="form-control" placeholder="bKash TrxID:" required>
          </div>
          <div class="form-group">
            <label for="address">Address:<span class="text-danger">*</span></label>
            <input type="text" name="address" id="address" class="form-control" placeholder="# 193,east-kazipara,mirpur-10,Dhaka" required>
          </div>
          <div class="form-group">
            <label for="phone">Phone No:<span class="text-danger">*</span></label>
            <input type="text" name="phone" id="phone" class="form-control" placeholder="018******" required>
          </div>
            <input type="submit" class="btn btn-info float-right" value="Check Out">
          </form>
          <div class="paymentinst" id="paymentinst">
            <hr><br><br>
            <h5 class="text-waring">***How to Make Payment with bKash:</h5><hr>
            <ol>
              <li>Go to your bkash Mobile Menu by dialing *247#</li>
              <li>Choose "Payment"</li>
              <li>Enter the Merchant bKash Wallet No: 01879205233</li>
              <li>Enter the Amount: {{ products|total_cart_price:request.session.cart|currency }}</li>
              <li>Enter Reference: 33{{ request.session.customer }}</li>
              <li>Enter the Counter Number: 123</li>
              <li>Now enter your bkash Menu PIN to Confirm</li>
              <li>Done! you will receive a confirmation message from bKash</li>
              <li>Put the Transaction ID in the Upper box and press "Checkout"</li>
            </ol>
          </div>
        </div>
      </div>

    </div>
  </div>
</div>
{% endif %}

<!-- end model -->

{% endblock %}

templates/editinfo.html
{% extends 'base.html' %}
{% load crispy_forms_tags %}

{% block title %}
Edit info
{% endblock title %}

{% block content %}
<div class="container">
    <div class="row m-3">
        <div class="border offset-3 col-md-6 border-success">
            <h1 class="text-center">Edit info Page</h1> <hr>
            <form method="post" action="{% url 'editUserInfo' %}" class="m-3" enctype="multipart/form-data">
                {% csrf_token %}
                {{ form|crispy }}
                {{ form1|crispy }}
                <input type="submit" class="btn btn-success m-3 w-100 mx-auto" value="Edit Now">
            
            </form>
        </div>
    </div>
</div>
{% endblock content %}

templates/index.html
{% extends 'base.html' %}
{% load mycheck %}


{% block title %}
Home
{% endblock %}

{% comment %} body {% endcomment %}
{% block content %}

<div class="container-fluid">
    <div class="row">
        <!-- menu item list -->
        <div class="col-lg-2 mt-3 mx-auto">
            <div class="list-group">
                <a href="/" class="list-group-item list-group-item-action active">All Products</a>
                {% for category in categories %}
                <a href="/?category={{category.id}}"
                    class="list-group-item list-group-item-action">{{ category.name }}</a>
                {% endfor %}
            </div>
        </div>

        <!-- all product list -->
        <div class="col-lg-10 mx-auto">
            <div class="row">
                {% for product in products %}
                <div class="col-md-3 col-sm-4" id = {{product.id}}>
                    <div class="card m-2">
                        <a href="{% url 'productdetail' product.id %}">
                        <img src="{{ product.image.url }}" alt="" height="250px" width="250px" class="card-img-top">
                        </a>

                        <div class="card-body">
                            <p>{{product.name}}</p>
                            <p>{{product.price|currency}}/{{product.unit}}</p>
                        </div>
                        <div class="card-footer no-gutters">
                            
                            {% if product|is_in_cart:request.session.cart %}
                            <div class="row">
                                <form action="/#{{product.id}}" class="col-3 p-0 btn btn-block btn-success" method="post">
                                    {% csrf_token %}
                                    <input type="text" hidden name="productid" value="{{product.id}}" id="">
                                    <input type="text" hidden name="remove" value="True" id="">
                                    <input type="submit" class='m-0 btn btn-success  btn-block ' value="-">
                                </form>
                                <div class="border text-center col">{{product|cart_quantity:request.session.cart}} {{product.unit}}</div>
                                <form action="/#{{product.id}}" class="col-3 p-0 btn btn-block btn-success" method="post">
                                    {% csrf_token %}
                                    <input type="text" hidden name="productid" value="{{product.id}}" id="">
                                    <input type="submit" class='btn btn-success  btn-block ' value="+">
                                </form>
                            </div>
                            {% else %}
                            <form action="/#{{product.id}}" class="btn-block" method="post">
                                {% csrf_token %}
                                <input type="text" hidden name="productid" value="{{product.id}}" id="">
                                <input type="submit" class='btn btn-success  btn-block ' value="Add to Card">
                            </form>
                            {% endif %}

                        </div>
                    </div>
                </div>
                {% empty %}
                <h1 class="mt-2 text-center text-danger">{{ message }}</h1>
                {% endfor %}

                 <!-- paginator -->
              <div class="container"><br>
                {% if products.has_other_pages %}
                <ul class="pagination justify-content-center ">
                  {% if products.has_previous %}
                    <li class="page-item"><a class="page-link" href="?productview={{ products.previous_page_number }}">Previous</a></li>
                  {% else %}
                    <li class="page-item"><a class="page-link disabled" href="javascript:void(0);">Previous</a></li>
                  {% endif %}
                  {% for i in products.paginator.page_range %}
                  {% if products.number == i %}
                  <li class="page-item"><a class="page-link active bg-danger text-light" href="javascript:void(0);">{{ i }}</a></li>
                  {% else %}
                  <li class="page-item"><a class="page-link" href="?productview={{ i }}">{{ i }}</a></li>
                  {% endif %}
                  {% endfor %}
                  {% if products.has_next %}
                  <li class="page-item"><a class="page-link" href="?productview={{ products.next_page_number }}">Next</a></li>
                  {% else %}
                  <li class="page-item"><a class="page-link" href="javascript:void(0);">Next</a></li>
                  {% endif %}
                </ul>
                {% endif %}<br>
              </div>
            <!-- end paginator -->

            </div>
        </div>
    </div>
</div>

{% endblock %}

templates/navbar.html
{% load mycheck %}

<nav class="navbar navbar-expand-md navbar-dark bg-dark">
  <a class="navbar-brand" href="{% url 'home' %}">Proyojon Shop</a>
  <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
    <span class="navbar-toggler-icon"></span>
  </button>

  <div class="collapse navbar-collapse" id="navbarSupportedContent">
    <ul class="navbar-nav mx-auto">
      {% if request.path|checkpath == '' %}
      <li class="nav-item">
        <a class="nav-link active" href="{% url 'home' %}">Home</a>
      </li>
      {% else %}
      <li class="nav-item">
        <a class="nav-link" href="{% url 'home' %}">Home</a>
      </li>
      {% endif %}
    </ul>
    
    <form action="{% url 'ProductSearch' %}" method="GET" class="form-inline mx-auto my-2 my-lg-0">
      <input type="text" value="{{mysearch}}" name="search" class="form-control form-control-md form-control-sm mr-sm-2" placeholder="Search" aria-label="Search">
      <input class="btn btn-sm btn-md btn-outline-success my-2 my-sm-0" type="submit" value = "Search"/>
    </form>

    <ul class="navbar-nav mr-0">
      {% if request.path|checkpath == 'cart' %}
      <li class="nav-item">
          <a class="nav-link active" aria-current="page" href="{% url 'cart' %}">Cart  
            {% if request.session.cart %}
            <small class="badge bg-info"> {{request.session.cart.keys|length}} </small>
            {% else %}
            <small class="badge bg-danger"> 0 </small>
            {% endif %}
          </a>
      </li>
      {% else %}
      <li class="nav-item">
          <a class="nav-link" aria-current="page" href="{% url 'cart' %}">Cart  
            {% if request.session.cart %}
            <small class="badge bg-info"> {{request.session.cart.keys|length}} </small>
            {% else %}
            <small class="badge bg-danger"> 0 </small>
            {% endif %}
          </a>
      </li>
      {% endif %}      
      {% if request.user.is_authenticated %}
          {% if request.path|checkpath == 'userprofile' %}
            <li class="nav-item active">
              <a class="nav-link" href="{% url 'userprofile' %}">{{request.user.first_name|upper}} {{request.user.last_name|upper}}</a>
            </li>
          {% else %}
            <li class="nav-item">
              <a class="nav-link" href="{% url 'userprofile' %}">{{request.user.first_name|upper}} {{request.user.last_name|upper}}</a>
            </li>
          {% endif %}
        <li class="nav-item">
          <a class="nav-link" href="{% url 'signout' %}">Logout</a>
        </li>
      {% else %}
        <li class="nav-item dropdown">
          <a class="nav-link dropdown-toggle" href="#" id="navbarDropdown" role="button" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
            Login/Signup
          </a>
          <div class="dropdown-menu" aria-labelledby="navbarDropdown">
            {% if request.path|checkpath == 'signin' %}
            <a class="dropdown-item active" href="{% url 'signin' %}">Login</a>
            {% else %}
            <a class="dropdown-item" href="{% url 'signin' %}">Login</a>
            {% endif %}
            <div class="dropdown-divider"></div>
            {% if request.path|checkpath == 'signup' %}
            <a class="dropdown-item active" href="{% url 'signup' %}">Sign Up</a>
            {% else %}
            <a class="dropdown-item" href="{% url 'signup' %}">Sign Up</a>
            {% endif %}
          </div>
        </li>
      {% endif %}
      
    </ul>
    </ul>
  </div>
</nav>

templates/productDetail.html
{% extends 'base.html' %}
{% load mycheck %}


{% block title %}
Prodcut Details
{% endblock %}

{% comment %} body {% endcomment %}
{% block content %}

<div class="container mt-5">
        <h3 class="text-center">Product Details</h3><hr>
    <div class="row">
        <div class="col-md-4 col-sm-12">
            <img src="{{ product.image.url }}" class="border rounded" alt="" height="250px" width="250px" class="card-img-top"><br>
        </div>
        <div class="col-md-8 col-sm-12 border">
            <div class="col-md-12 mt-3">
                <u>Name:</u>
                <h3>{{ product.name }}</h3>
                <u>Price:</u>
                <h3>{{ product.price }} / {{ product.unit }}</h3>
                <u>Description:</u>
                <p>{{ product.description }} </p>
                <u>Category:</u>
                <h3 class="mx-auto tex-center">{{ product.category }}</h3>

            </div>
        </div>
    </div>
</div>
{% endblock %}

templates/userprofile.html
{% extends 'base.html' %}
{% load static %}
{% load mycheck %}


{% block title %}
Profile
{% endblock %}

{% comment %} body {% endcomment %}
{% block content %}

<div class="container-fluid">
    <div class="row mt-3">
        <!-- start user profile area left side -->
        <div class="col-md-3 mx-auto ">
          <div class="border p-2 w-100">
            <h1 class='text-center'>User Profile</h1><hr>
            {% if profile.profile_pic %}
            <img class='d-block mx-auto img-thumbnail' src="{{ profile.profile_pic.url }}" alt="">
            {% else %}
            <img class='d-block mx-auto img-thumbnail' src="{% static 'image/demoprofile.png' %}" alt="">
            {% endif %}
            <p>Name: {{ user.first_name}} {{ user.last_name }}</p>
            <p>Email: {{ user.email }}</p>
            <p>Gender: {{profile.get_gender_display}}</p>
            <p>Address: {{profile.address}}</p>
            <p>Phone No: {{profile.phone}}</p>
            <div class="row">
                <div class="col">
                    <a href="{% url 'editUserInfo' %}" class="btn btn-success w-100">Edit</a>
                </div>
                <div class="col">
                    <a href="{% url 'home' %}" class="btn btn-warning w-100">Change password</a>
                </div>
            </div>
            </div>
        </div>
        <!-- end user profile or left side -->

        <!-- start right side -->
        <div class="col-md-8">
            <h4 class="text-center">User Details</h4>
            
            {% if request.user.is_superuser %}
            <div class="row mx-auto">
                <div class="col">
                    <a href="{% url 'addproduct' %}" class="btn btn-info m-1">Add Product</a>
                </div>
                <div class="col">
                    <a href="{% url 'addcategory' %}" class="btn btn-warning m-1">Add Category</a>
                </div>
                <div class="col">
                    <a href="{% url 'catAndprod' %}" class="btn btn-warning m-1">Categorys/Products</a>
                </div>
                <div class="col">
                    <a href="{% url 'orderview' %}" class="btn btn-warning m-1">Order View</a>
                </div>
            </div>
            {% endif %}
            
            {% comment %} Start superuseradmin view {% endcomment %}
            {% if request.user.is_superuser %}

            <!-- start revenew area -->
            <div class="row">
                <div class="col-xl-3 col-lg-6 col-md-6 col-sm-6">
                    <div class="card card-stats">
                      <div class="card-header card-header-success card-header-icon">
                        <div class="card-icon">
                          <i class="material-icons">store</i>
                        </div>
                        <p class="card-category">Revenue</p>
                        <h3 class="card-title">৳ {{ revenewsum }}</h3>
                      </div>
                      <div class="card-footer">
                        <div class="stats">
                          <i class="material-icons">date_range</i> ALL Time
                        </div>
                      </div>
                    </div>
                </div>
            </div>
            <!-- end revenew area -->

            
            {% endif %}

            {% comment %} end superuseradmin view {% endcomment %}

            <!-- user order product view -->
            <div class="row">
                <div class="border rounded p-4 m-1">
                    <h1 class='text-center'>Your Orders</h1>
                    <table class="table">
                      <thead>
                        <tr>
                          <th>Sno.</th>
                          <th>Image</th>
                          <th>Name</th>
                          <th>Category</th>
                          <th>Date</th>
                          <th>Price</th>
                          <th>Quantity</th>
                          <th>Total Price</th>
                          <th>Status</th>
                        </tr>
                      </thead>
                      <tbody>
                        
                    {% for order in orders %}
                        <tr>          
                          <td>{{ forloop.counter }}</td>
                          <td><img src="{{ order.product.image.url }}" width="100px" height="100px" alt=""></td>
                          <td>{{ order.product.name}}</td>
                          <td>{{ order.product.category}}</td>
                          <td>{{ order.date}}</td>
                          <td>{{ order.price|currency }}</td>
                          <td>{{ order.quantity}}</td>
                          <td>{{ order.quantity|multiply:order.price|currency }}</td>
                          {% if order.status %}
                          <td><small class="badge badge-success p-3">Completed</small></td>
                          {% else %}
                          <td><small class="badge badge-danger p-3">Pangding</small></td>
                          {% endif %}
                        </tr>
                    {% endfor %}
                        
                      </tbody>
                      
                    </table>
                
                   
                  </div>
            </div>
            <!-- order product view end -->

        </div>
    </div>


</div>

{% endblock content %}